{
 "title": "KubeEvents from OpenSearch",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "K8S Events per Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "firstTimestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "firstTimestamp"
    }
   ]
  },
  {
   "title": "K8S Events per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "metadata.namespace.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "firstTimestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "metadata.creationTimestamp"
    }
   ]
  },
  {
   "title": "K8S Events Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "timeField": "metadata.creationTimestamp"
    }
   ]
  }
 ]
}